version: "3.9"

services:
  app_contempret:
    image: app_contempret:latest
    build:
      context: .
    volumes:
      - ./bin:/app/bin
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: -1
            capabilities: [gpu]
